import type { User, Post } from "@/types/data";

export const DUMMY_USERS: User[] = [
  {
    id: "u1",
    username: "alice",
    name: "Alice Kim",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    bio: "Frontend Developer",
  },
  {
    id: "u2",
    username: "bob",
    name: "Bob Lee",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    bio: "Backend Engineer",
  },
  {
    id: "u3",
    username: "carol",
    name: "Carol Park",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    bio: "Fullstack Enthusiast",
  },
  {
    id: "u4",
    username: "daniel",
    name: "Daniel Choi",
    image: "https://randomuser.me/api/portraits/men/43.jpg",
    bio: "DevOps Specialist",
  },
  {
    id: "u5",
    username: "eve",
    name: "Eve Jung",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    bio: "UI/UX Designer",
  },
];

export const DUMMY_POSTS: Post[] = [
  {
    id: "p1",
    createdAt: "2025-06-16T09:00:00Z",
    content: "안녕하세요! Threads 클론 프로젝트 시작합니다.",
    user_id: "u1",
    user: DUMMY_USERS[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p2",
    createdAt: "2025-06-16T09:05:00Z",
    content: "환영합니다! 모두 화이팅해요 💪",
    user_id: "u2",
    user: DUMMY_USERS[1],
    parent_id: "p1",
    parent: null,
    replies: [],
  },
  {
    id: "p3",
    createdAt: "2025-06-16T09:10:00Z",
    content: "디자인 시안 곧 공유드릴게요.",
    user_id: "u5",
    user: DUMMY_USERS[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p4",
    createdAt: "2025-06-16T09:12:00Z",
    content: "API 명세는 어디서 볼 수 있나요?",
    user_id: "u3",
    user: DUMMY_USERS[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p5",
    createdAt: "2025-06-16T09:15:00Z",
    content: "Notion에 정리해두었습니다!",
    user_id: "u1",
    user: DUMMY_USERS[0],
    parent_id: "p4",
    parent: null,
    replies: [],
  },
  {
    id: "p6",
    createdAt: "2025-06-16T09:20:00Z",
    content: "CI/CD 파이프라인 구축 완료!",
    user_id: "u4",
    user: DUMMY_USERS[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p7",
    createdAt: "2025-06-16T09:22:00Z",
    content: "테스트 코드도 추가해볼게요.",
    user_id: "u2",
    user: DUMMY_USERS[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p8",
    createdAt: "2025-06-16T09:25:00Z",
    content: "좋아요! 코드 리뷰 부탁드려요.",
    user_id: "u3",
    user: DUMMY_USERS[2],
    parent_id: "p7",
    parent: null,
    replies: [],
  },
  {
    id: "p9",
    createdAt: "2025-06-16T09:30:00Z",
    content: "이미지 업로드 기능은 어떻게 할까요?",
    user_id: "u5",
    user: DUMMY_USERS[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p10",
    createdAt: "2025-06-16T09:35:00Z",
    content: "S3 연동을 고려해볼 수 있을 것 같아요.",
    user_id: "u4",
    user: DUMMY_USERS[3],
    parent_id: "p9",
    parent: null,
    replies: [],
  },
  {
    id: "p11",
    createdAt: "2025-06-16T09:40:00Z",
    content: "프론트엔드에서 미리보기 구현해볼게요.",
    user_id: "u1",
    user: DUMMY_USERS[0],
    parent_id: "p9",
    parent: null,
    replies: [],
  },
  {
    id: "p12",
    createdAt: "2025-06-16T09:45:00Z",
    content: "다들 고생 많으십니다!",
    user_id: "u2",
    user: DUMMY_USERS[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p13",
    createdAt: "2025-06-16T09:50:00Z",
    content: "오늘 회의는 2시에 진행할게요.",
    user_id: "u3",
    user: DUMMY_USERS[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "p14",
    createdAt: "2025-06-16T09:55:00Z",
    content: "네, 일정 확인했습니다!",
    user_id: "u5",
    user: DUMMY_USERS[4],
    parent_id: "p13",
    parent: null,
    replies: [],
  },
  {
    id: "p15",
    createdAt: "2025-06-16T10:00:00Z",
    content: "회의록은 제가 정리하겠습니다.",
    user_id: "u4",
    user: DUMMY_USERS[3],
    parent_id: "p13",
    parent: null,
    replies: [],
  },
];
